### ISSUE TITLE
Cannot create producer on Python 3.5

### ISSUE THREAD

**Issue by spudfkc** [Parsely/pykafka#407]
I'm trying to create a simple producer in Python 3.5 and come across the following error message:
```
  File "/app/.tox/py35/lib/python3.5/site-packages/pykafka/topic.py", line 88, in get_producer
    return Cls(self._cluster, self, **kwargs)
  File "/app/.tox/py35/lib/python3.5/site-packages/pykafka/producer.py", line 152, in __init__
    self.start()
  File "/app/.tox/py35/lib/python3.5/site-packages/pykafka/producer.py", line 189, in start
    self._setup_owned_brokers()
  File "/app/.tox/py35/lib/python3.5/site-packages/pykafka/producer.py", line 228, in _setup_owned_brokers
    self, partition.leader)
  File "/app/.tox/py35/lib/python3.5/site-packages/pykafka/producer.py", line 426, in __init__
    self.lock = self.producer._cluster.handler.RLock()
  File "/usr/lib/python3.5/threading.py", line 82, in RLock
    return _PyRLock(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'verbose'
```

I've tracked the problem down to the following line in `pykafka/handlers.py`:
```python
    # turn off RLock's super annoying default logging
    RLock = functools.partial(threading.RLock, verbose=False)
```

So, what this seems to be doing is instantiating a new RLock, which is fine. But if we take a look at python 3.5's `threading.py` we see the following (I removed unnecessary info):

```python
try:
    _CRLock = _thread.RLock
except AttributeError:
    _CRLock = None
 
   ...

def RLock(*args, **kwargs):
    if _CRLock is None:
        return _PyRLock(*args, **kwargs)
    return _CRLock(*args, **kwargs)

  ...

class _RLock:
    def __init__(self):
       ...

   ...

_PyRLock = _RLock
```

As you can see, if we don't have a CRLock, we end up using a PyRLock, which does not take any arguments. This causes the producer to fail being created since it gets an unexpected keyword argument.

**Comment by emmett9001** [comment]
Thanks @spudfkc, this is an annoying one. Turning off the logging is quite necessary, since it gets in the way of all of the other logging that pykafka does and makes reading posted logs really difficult. Checking the type of the lock as it's created isn't super appealing, because we use that `RLock` class attribute all over the place. Maybe I can set up a callable here in place of the `partial` that performs a type check and conditionally includes the kwarg.

**Comment by spudfkc** [comment]
Workaround thanks to @timmartin19:
```
# invoke this before you run into the error
handlers.ThreadingHandler.RLock = staticmethod(threading.RLock)
```

**Comment by emmett9001** [comment]
Thanks @spudfkc! Any information on why this works? It seems kind of magical, but if I understand the reason it works I can probably include it in pykafka.

**Comment by timmartin19** [comment]
It was actually @akatrevorjay who came up with the solution.  It's a monkeypatch to get it to work in python3.5.  Basically, we're just overwriting the RLock attribute which was originally the partial.  A better fix would look something like:

    import threading
    
    class ThreadingHandler(object):
        def RLock(*args, **kwargs):
            kwargs['verbose'] = False
            try:
                return threading.RLock(*args, **kwargs)
            except TypeError:
                kwargs.pop('verbose')
                return threading.RLock(*args, **kwargs)

I can submit a tested pull request if you want.

**Comment by emmett9001** [comment]
@timmartin19 Ok, makes sense that your solution only works in 3.5. If you'd like to submit a pull request, that would be great. Thanks!

**Comment by emmett9001** [comment]
I can grab this and open a pull request.
