### ISSUE TITLE
Bug in gevent 1.3.x triggers problem publishing with delivery_reports enabled

### ISSUE THREAD

**Issue by bpowers39** [Parsely/pykafka#852]
Due to a Gevent bug here https://github.com/gevent/gevent/issues/1266, publishing synchronously, or with delivery_reports error results in a exception being thrown.

Python Version: 3.6.5
Pykafka Version: 2.6.0
Gevent Version: 1.3.4 (works with 1.1.0)

### Example Stack Trace
```
  File "/bb/bin/ibwebapi-dependencies.zip/pykafka/producer.py", line 333, in produce
    self._raise_worker_exceptions()
  File "/bb/bin/ibwebapi-dependencies.zip/pykafka/producer.py", line 197, in _raise_worker_exceptions
    reraise(*self._worker_exception)
  File "/opt/bb/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/bb/bin/ibwebapi-dependencies.zip/pykafka/producer.py", line 537, in queue_reader
    self.producer._send_request(batch, self)
  File "/bb/bin/ibwebapi-dependencies.zip/pykafka/producer.py", line 428, in _send_request
    mark_as_delivered(messages)
  File "/bb/bin/ibwebapi-dependencies.zip/pykafka/producer.py", line 410, in mark_as_delivered
    self._delivery_reports.put(msg)
  File "/bb/bin/ibwebapi-dependencies.zip/pykafka/producer.py", line 685, in put
    msg.delivery_report_q.put((msg, exc))
  File "src/gevent/local.py", line 455, in gevent._local.local.__getattribute__
AttributeError: '_DeliveryReportQueue' object has no attribute 'delivery_report_q'
```

To work around this issue temporarily, I patched the producer to drop the ```@staticmethod``` decorator on the _DeliveryReportQueue class. There doesn't seem to be a good reason these functions are static. I've attached the patch below. Not sure this is worth a PR, since it will be fixed upstream soon, but I figured I'd mention it here in case anyone else runs into this issue.

```diff
--- a/pykafka/producer.py
+++ b/pykafka/producer.py
@@ -680,8 +680,7 @@ class _DeliveryReportQueue(threading.local):
     def __init__(self, handler):
         self.queue = handler.Queue()

-    @staticmethod
-    def put(msg, exc=None):
+    def put(self, msg, exc=None):
         msg.delivery_report_q.put((msg, exc))


@@ -690,6 +689,5 @@ class _DeliveryReportNone(object):
     def __init__(self):
         self.queue = None

-    @staticmethod
-    def put(msg, exc=None):
+    def put(self, msg, exc=None):
         return
```

**Comment by emmett9001** [comment]
Thank you for the report @bpowers39. I think you're correct that this is a `wontfix` unless it takes awhile for the upstream fix to become available. I'll leave this ticket open until that time.

**Comment by jamadden** [comment]
The upstream issue [was fixed in gevent 1.3.6](http://www.gevent.org/changelog.html#id2), released on 2018-08-17.
