### ISSUE TITLE
Balanced consumer processes keep "exiting cleanly"

### ISSUE THREAD

**Issue by eltermann** [Parsely/pykafka#606]
Hi,

I recently updated to pykafka-2.5.0 and noticed two strange behaviors.

Environment:

* pykafka-2.5.0
* topic with 64 partitions
* consumers running in 3 servers (in each server, all log msgs go to the same output file)
 * server 1: 2 processes
 * server 2: 6 processes
 * server 3: 36 processes (unable to increase because of the behaviors detailed below)
* each process instantiate a balanced_consumer with:
 * consumer_group="same_group_for_all"
 * auto_commit_enable=True
 * auto_commit_interval_ms=15000
 * consumer_timeout_ms=10000
 * zookeeper_connect="[kafkazookeeper]"
 * auto_offset_reset=OffsetType.LATEST
 * reset_offset_on_start=False

Strange behavior 1 - some processes get stuck in "exiting cleanly" loop
===

When I start processes one at a time, some processes get stuck in a loop, generating the following log pattern.
(note that other processes normally consume messages)

Server 1 (2 processes)
```
[other process doing time-consuming task]
2016-10-06 10:45:15,400 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:45:16,351 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:45:25,449 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:45:26,450 : INFO : RequestHandler worker: exiting cleanly
[other process doing time-consuming task]
```

Server 2 (6 processes)
```
[other processes doing time-consuming tasks]
2016-10-06 10:51:23,855 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:51:24,247 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:51:24,601 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:51:24,832 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:51:25,222 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:51:25,582 : INFO : RequestHandler worker: exiting cleanly
[other processes doing time-consuming tasks]
```

Server 3 (36 processes)
```
[things get messy, but it is possible to identify patterns like the following]
[other processes doing time-consuming tasks]
2016-10-06 10:59:37,067 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:59:37,107 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:59:37,200 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:59:37,205 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:59:38,099 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:59:38,191 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:59:38,650 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:59:39,430 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:59:39,493 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:59:39,639 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:59:39,650 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 10:59:39,708 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 10:59:40,109 : INFO : RequestHandler.stop: about to flush requests queue
[other processes doing time-consuming tasks]
```

Strange behavior 2 - flood of PartitionOwnedError exceptions
===

When starting all processes at the same time, log files are flooded with fast thousands of the message bellow. No consuming activity is logged. Processes get stuck like this until I stop them.

```
2016-10-06 10:25:21,759 : ERROR : Consumer error. Exception: PartitionOwnedError()
```

**Comment by emmett9001** [comment]
Thanks @eltermann. In scenario 1, are there any messages before the looping pattern about a rebalance? Also, just to be clear, are these looping consumers failing to successfully consume messages?

To scenario 2, I'd be interested to know more about the client code you're using to run the consumers. At Parsely, we start multiple processes on the same VM running under Storm at very close to the same moment, and we generally don't see behavior like this. Might there be some confounding circumstance in your client code that's causing the consumer to behave differently?

**Comment by eltermann** [comment]
@emmett9001,

Regarding scenario 1: the pattern seems to be happening just after (or during) a rebalance. Also, no messages are consumed (process logs other messages for each processed message). After isolating log messages for only one process I got the following:

```
2016-10-06 15:20:12,074 : INFO : Could not load pykafka.rdkafka extension.
Traceback (most recent call last):
	[traceback removed]
ImportError: cannot import name _rd_kafka
2016-10-06 15:20:14,068 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:20:14,068 : INFO : Discovered 1 brokers
2016-10-06 15:20:14,070 : INFO : Discovered 65 topics
2016-10-06 15:20:14,074 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:20:14,075 : INFO : Adding 64 partitions
2016-10-06 15:20:14,076 : INFO : Connecting to ...
2016-10-06 15:20:14,092 : INFO : Zookeeper connection established, state: CONNECTED
2016-10-06 15:20:14,121 : INFO : Rebalancing consumer "..." for topic "...".
2016-10-06 15:20:14,151 : INFO : ...: Balancing 39 participants for 64 partitions. Owning 1 partitions.
2016-10-06 15:20:14,217 : INFO : Attempting to discover offset manager for consumer group '...'
2016-10-06 15:20:14,235 : INFO : Found coordinator broker with id 0
2016-10-06 15:20:14,239 : INFO : Starting 1 fetcher threads
2016-10-06 15:20:14,240 : INFO : Rebalancing Complete.
2016-10-06 15:20:15,042 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:20:15,075 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:20:24,266 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:20:25,246 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:20:34,300 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:20:35,272 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:20:44,333 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:20:45,309 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:20:54,361 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:20:55,339 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:21:04,388 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:21:05,366 : INFO : RequestHandler worker: exiting cleanly
...
```

Regarding scenario 2, it happens both for bare-metal and VM machines. We built some kind of batch-processing framework. From times to times, a producer process read information from database and produce a to-be-processed stream directly to Kafka. Listening consumers then start their work. The consumer client code basically read arguments, configure kafka and other stuff. It then basically enter in an infinite while loop:

```python
while True:
    log = kafkaconsumer.consume()
```

(exception handling and other things are also performed, but this is the core regarding to kafka)

Thank YOU.

**Comment by eltermann** [comment]
For the sake of experimentation, I stopped/started this one process 3 times. This is the log.

```
2016-10-06 15:40:27,408 : INFO : Could not load pykafka.rdkafka extension.
ImportError: cannot import name _rd_kafka
[INITIALIZATION MESSAGES]
2016-10-06 15:40:29,648 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:40:29,649 : INFO : Discovered 1 brokers
2016-10-06 15:40:29,651 : INFO : Discovered 65 topics
2016-10-06 15:40:29,659 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:40:29,660 : INFO : Adding 64 partitions
2016-10-06 15:40:29,663 : INFO : Connecting to ...
2016-10-06 15:40:29,678 : INFO : Zookeeper connection established, state: CONNECTED
2016-10-06 15:40:29,693 : INFO : Rebalancing consumer "" for topic "".
2016-10-06 15:40:29,747 : INFO : ...: Balancing 39 participants for 64 partitions. Owning 1 partitions.
2016-10-06 15:40:29,829 : INFO : Attempting to discover offset manager for consumer group '...'
2016-10-06 15:40:29,867 : INFO : Found coordinator broker with id 0
2016-10-06 15:40:29,872 : INFO : Starting 1 fetcher threads
2016-10-06 15:40:29,874 : INFO : Rebalancing Complete.
2016-10-06 15:40:30,604 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:40:30,660 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:40:39,929 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:40:40,896 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:40:50,001 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:40:50,948 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:41:02,595 : INFO : Could not load pykafka.rdkafka extension.
ImportError: cannot import name _rd_kafka
[INITIALIZATION MESSAGES]
2016-10-06 15:41:04,846 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:41:04,846 : INFO : Discovered 1 brokers
2016-10-06 15:41:04,849 : INFO : Discovered 65 topics
2016-10-06 15:41:04,857 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:41:04,857 : INFO : Adding 64 partitions
2016-10-06 15:41:04,860 : INFO : Connecting to ...
2016-10-06 15:41:04,875 : INFO : Zookeeper connection established, state: CONNECTED
2016-10-06 15:41:04,889 : INFO : Rebalancing consumer "..." for topic "...".
2016-10-06 15:41:04,915 : INFO : ...: Balancing 39 participants for 64 partitions. Owning 1 partitions.
2016-10-06 15:41:04,949 : INFO : Unable to acquire partition <pykafka.partition.Partition at 0x3b4c310 (id=60)>. Retrying
2016-10-06 15:41:04,970 : INFO : ...: Balancing 39 participants for 64 partitions. Owning 1 partitions.
2016-10-06 15:41:05,007 : INFO : Attempting to discover offset manager for consumer group '...'
2016-10-06 15:41:05,014 : INFO : Found coordinator broker with id 0
2016-10-06 15:41:05,018 : INFO : Starting 1 fetcher threads
2016-10-06 15:41:05,019 : INFO : Rebalancing Complete.
2016-10-06 15:41:05,796 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:41:05,853 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:41:20,042 : INFO : Could not load pykafka.rdkafka extension.
ImportError: cannot import name _rd_kafka
[INITIALIZATION MESSAGES]
2016-10-06 15:41:22,027 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:41:22,027 : INFO : Discovered 1 brokers
2016-10-06 15:41:22,029 : INFO : Discovered 65 topics
2016-10-06 15:41:22,037 : INFO : RequestHandler.stop: about to flush requests queue
2016-10-06 15:41:22,038 : INFO : Adding 64 partitions
2016-10-06 15:41:22,042 : INFO : Connecting to ...
2016-10-06 15:41:22,059 : INFO : Zookeeper connection established, state: CONNECTED
2016-10-06 15:41:22,086 : INFO : Rebalancing consumer "..." for topic "...".
2016-10-06 15:41:22,118 : INFO : ...: Balancing 39 participants for 64 partitions. Owning 1 partitions.
2016-10-06 15:41:22,174 : INFO : Attempting to discover offset manager for consumer group '...'
2016-10-06 15:41:22,196 : INFO : Found coordinator broker with id 0
2016-10-06 15:41:22,200 : INFO : Starting 1 fetcher threads
2016-10-06 15:41:22,202 : INFO : Rebalancing Complete.
2016-10-06 15:41:22,994 : INFO : RequestHandler worker: exiting cleanly
2016-10-06 15:41:23,038 : INFO : RequestHandler worker: exiting cleanly
```

**Comment by emmett9001** [comment]
Thanks. Just to be clear, are these issues that appeared in previously working code after upgrading to pykafka 2.5.0? If so, what was the previous version you were using?

**Comment by eltermann** [comment]
These issues started when upgrading from 1.0.3 to 2.5.0.

Before, it worked fine (except for the issue mentioned [here](https://groups.google.com/forum/#!topic/pykafka-user/-LQ8vkATqBA))

**Comment by emmett9001** [comment]
Thanks - there have been a ton of changes since 1.0.3, so unfortunately this doesn't narrow down the problem space for this issue too much.

**Comment by eltermann** [comment]
I found I was performing some work-arounds that seem to not be necessary in version 2.5.0 and those were leading to the strange behavior + excessive messages.

Simplified it and works fine with version 2.5.0 now.

**Comment by emmett9001** [comment]
Glad you were able to resolve this!
